### PR TITLE
fix: add DB_DSN support

### PR DESCRIPTION
**Pull request by andhreljaKern**

### CODE REVIEW

**Comment by lumburovskalina** [comment]
I am getting this error when i tried to start the websockets  
Screenshot 2024-08-30 at 13 34 41

- [ ] resolved
- [ ] ignored

**Comment by lumburovskalina** [comment]
Not sure but this doesn't look like the expected behaviour

Screenshot 2024-08-30 at 13 36 17

- [ ] resolved
- [ ] ignored

**Comment by andhreljaKern** [comment]
> I am getting this error when i tried to start the websockets Screenshot 2024-08-30 at 13 34 41
> 
> * [ ]  resolved
> * [ ]  ignored

This must be due to the `host` config in refinery-websocket start script. Looking at the start script, I see we can revert the changes made and only update DB_DSN value via https://github.com/code-kern-ai/tf-azure-refinery-websocket/

**Comment by andhreljaKern** [comment]
Closed as not needed

**Pull request closed without merging**
